---
actions:
  1:
    action: delete_indices
    options:
      ignore_empty_list: true
      continue_if_exception: false
      disable_action: false
    filters:
      - filtertype: pattern
        kind: prefix
        value: fluentd-
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y-%m-%d_%H:%M:%S'
        unit: days
        unit_count: 1